### ISSUE TITLE
Error opening InputStream: Invalid sample rate [PaErrorCode -9997]

### ISSUE THREAD

**Issue by faveoled** [chidiwilliams/buzz#10]
![image](https://user-images.githubusercontent.com/85760289/193409775-d6b20c1d-f631-4998-b5a1-2a412422c3af.png)

Running Ubuntu 22.04.1. Trying to run with default HDA intel Mic results in the following error. (Options "pulse" and "default" work on the surface but appear silent).
```
user@hp-laptop:~/Downloads/buzz$ poetry run python main.py
[2022-10-01 15:28:39,667] transcriber.start_recording:42 DEBUG -> Recording... language: "en", model: "tiny", task: "Task.TRANSCRIBE", device: "5", block duration: "10"
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2718
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2842
Traceback (most recent call last):
  File "/home/user/Downloads/buzz/gui.py", line 266, in on_status_changed
    self.start_recording()
  File "/home/user/Downloads/buzz/gui.py", line 292, in start_recording
    self.transcriber.start_recording(
  File "/home/user/Downloads/buzz/gui.py", line 182, in start_recording
    self.transcriber.start_recording(
  File "/home/user/Downloads/buzz/transcriber.py", line 44, in start_recording
    self.current_stream = sounddevice.InputStream(
  File "/home/user/.cache/pypoetry/virtualenvs/buzz-DqnAh-gc-py3.10/lib/python3.10/site-packages/sounddevice.py", line 1421, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/home/user/.cache/pypoetry/virtualenvs/buzz-DqnAh-gc-py3.10/lib/python3.10/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/home/user/.cache/pypoetry/virtualenvs/buzz-DqnAh-gc-py3.10/lib/python3.10/site-packages/sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Invalid sample rate [PaErrorCode -9997]
Aborted (core dumped)

```

**Comment by chidiwilliams** [comment]
Try changing `whisper.audio.SAMPLE_RATE` to `44100` in these two lines:

https://github.com/chidiwilliams/buzz/blob/main/transcriber.py#L45-L46

Does it work when you try?

**Comment by chidiwilliams** [comment]
Also, what happens when you try with a different audio device?

**Comment by faveoled** [comment]
> Try changing `whisper.audio.SAMPLE_RATE` to `44100` in these two lines:

Original exception is gone. But nothing is recognized (I think it records silence), just with the other two options "pulse" and "default". The mic is on.
Also, Intel starts failing somewhere around the third attempt:
```
user@hp-laptop:~/Downloads/buzz$ poetry run python main.py
[2022-10-02 15:00:24,141] transcriber.start_recording:42 DEBUG -> Recording... language: "en", model: "tiny", task: "Task.TRANSCRIBE", device: "5", block duration: "10"
[2022-10-02 15:00:29,167] transcriber.stop_recording:79 DEBUG -> Closed recording stream
[2022-10-02 15:00:29,167] transcriber.stop_recording:85 DEBUG -> Waiting for processing thread to terminate
[2022-10-02 15:00:29,167] transcriber.stop_recording:87 DEBUG -> Processing thread terminated
[2022-10-02 15:00:47,283] transcriber.start_recording:42 DEBUG -> Recording... language: "en", model: "tiny", task: "Task.TRANSCRIBE", device: "5", block duration: "10"
[2022-10-02 15:00:52,076] transcriber.stop_recording:79 DEBUG -> Closed recording stream
[2022-10-02 15:00:52,076] transcriber.stop_recording:85 DEBUG -> Waiting for processing thread to terminate
[2022-10-02 15:00:52,076] transcriber.stop_recording:87 DEBUG -> Processing thread terminated
[2022-10-02 15:01:02,568] transcriber.start_recording:42 DEBUG -> Recording... language: "en", model: "tiny", task: "Task.TRANSCRIBE", device: "5", block duration: "10"
Expression 'ret' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1736
Expression 'AlsaOpen( &alsaApi->baseHostApiRep, params, streamDir, &self->pcm )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1904
Expression 'PaAlsaStreamComponent_Initialize( &self->capture, alsaApi, inParams, StreamDirection_In, NULL != callback )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2171
Expression 'PaAlsaStream_Initialize( stream, alsaHostApi, inputParameters, outputParameters, sampleRate, framesPerBuffer, callback, streamFlags, userData )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2839
Traceback (most recent call last):
  File "/home/user/Downloads/buzz/gui.py", line 291, in on_status_changed
    self.start_recording()
  File "/home/user/Downloads/buzz/gui.py", line 317, in start_recording
    self.transcriber.start_recording(
  File "/home/user/Downloads/buzz/gui.py", line 206, in start_recording
    self.transcriber.start_recording(
  File "/home/user/Downloads/buzz/transcriber.py", line 44, in start_recording
    self.current_stream = sounddevice.InputStream(
  File "/home/user/.cache/pypoetry/virtualenvs/buzz-DqnAh-gc-py3.10/lib/python3.10/site-packages/sounddevice.py", line 1421, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/home/user/.cache/pypoetry/virtualenvs/buzz-DqnAh-gc-py3.10/lib/python3.10/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/home/user/.cache/pypoetry/virtualenvs/buzz-DqnAh-gc-py3.10/lib/python3.10/site-packages/sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Device unavailable [PaErrorCode -9985]
Aborted (core dumped)
```

**Comment by faveoled** [comment]
Seems strange that processing thread terminates at the same time it starts

**Comment by chidiwilliams** [comment]
Yeah, I'm not sure what the issue is here. But looks like something to do with the microphone setup. Something else to try could be to test out a simple program like [this](https://linuxtut.com/en/b22900e7abab96964b85/#record_+_save) and see if you can get a recording out.

**Comment by faveoled** [comment]
> Something else to try could be to test out a simple program like [this](https://linuxtut.com/en/b22900e7abab96964b85/#record_+_save) and see if you can get a recording out.

I've checked and the recording is completely fine

**Comment by chidiwilliams** [comment]
I'll try to find a computer running Ubuntu to test this out myself, but if you're able to find a fix before then, I'd be happy to take your PR.

**Comment by faveoled** [comment]
I've now got some progress. At least it started printing something to the output (albeit not what I was saying) with my headphones off. Plus most my recordings were <10s which seemed to make Buzz not process them at all.

**Comment by chidiwilliams** [comment]
Okay, let me know what else you find. Will mark this as closed for now.

**Comment by faveoled** [comment]
Unless you expect the users to manually patch their sample rates within python source code this shouldn't be closed

**Comment by chidiwilliams** [comment]
I closed this because I'm unable to replicate the issue after trying different audio devices on both Windows and Mac. I'll reopen if I can find a computer running Ubuntu to test. If you have a fix that works, feel free to send a PR, and I'd be happy to have a look.

**Comment by chidiwilliams** [comment]
Could you try checking out this branch and testing with it? https://github.com/chidiwilliams/buzz/tree/use-default-sample-rate. I made a code change that might help.

**Comment by faveoled** [comment]
> Could you try checking out this branch and testing with it? https://github.com/chidiwilliams/buzz/tree/use-default-sample-rate. I made a code change that might help.

I guess it works - no exception is thrown there

**Comment by chidiwilliams** [comment]
> > Could you try checking out this branch and testing with it? https://github.com/chidiwilliams/buzz/tree/use-default-sample-rate. I made a code change that might help.
> 
> 
> 
> I guess it works - no exception is thrown there

Does the transcription work?

**Comment by faveoled** [comment]
No, I still receive empty results
