### ISSUE TITLE
Unhandled exception in script

### ISSUE THREAD

**Issue by mriamnobody** [chidiwilliams/buzz#1000]
# Environment

OS: Windows 11 (26100.2454)
Python: 3.10.7
CUDA Version: 12.1
ffmpeg version on path: 6.1.1

Downloaded and installed latest build from [here](https://github.com/chidiwilliams/buzz/actions/runs/11895449854) and getting the following error.

```
Failed to execute script 'main' due to unhandled exception:
tokenizers>=0.20,<0.21 is required for a normal functioning of
this module, but found tokenizers == 0.15.2.
Try: `pip install transformers -U' or `pip install -e '.[dev]" if you're
working with git main

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 58, in main
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "buzz\cli.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "buzz\widgets\application.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "buzz\widgets\main_window.py", line 23, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "buzz\file_transcriber_queue_worker.py", line 16, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "buzz\transcriber\whisper_file_transcriber.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "buzz\transformers_whisper.py", line 7, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "transformers\dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "transformers\utils\versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "transformers\utils\versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "transformers\utils\versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: tokenizers>=0.20,<0.21 is required for a normal functioning of this module, but found tokenizers==0.15.2.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
```

**Comment by raivisdejus** [comment]
@mriamnobody Short term fix is to uninstall old version before installing the new version of the Buzz.

**Comment by raivisdejus** [comment]
This is fixed in the latest development version https://chidiwilliams.github.io/buzz/docs/faq#9-where-can-i-get-latest-development-version
