### ISSUE TITLE
Import URL Immediate Cancel after Import

### ISSUE THREAD

**Issue by Jstorto21** [chidiwilliams/buzz#1001]
OS: Windows 10
Buzz Version: 1.1.0

Description:
When attempting to import a URL via the "File" > "Import URL" menu, the window closes unexpectedly. Upon reopening the application, the status of the import is shown as "Canceled." This issue is reproducible every time a URL is imported.

Steps to Reproduce:

Open the Buzz application.
Navigate to "File" > "Import URL."
Choose a URL to import and initiate the process.
Settings:
Model: Whisper, Base
Task: Transcribe
Language: French
Export: TXT
The import window closes, and the import status is shown as "Canceled" upon reopening the app.

Log Files:
Here are the relevant log entries from the attempted upload:

[2024-11-22 20:52:22,731] locale.<module>:12 DEBUG -> UI locales ['en-US', 'en-Latn-US', 'en']  
[2024-11-22 20:52:22,734] model_loader.<module>:42 DEBUG -> Model root directory: C:\Users\joest\AppData\Local\Buzz\Buzz\Cache\models  
[2024-11-22 20:52:23,841] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg6  
[2024-11-22 20:52:23,842] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg6 extension.  
Traceback (most recent call last):  
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension  
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension  
  File "<frozen importlib.util>", line 95, in find_spec  
ModuleNotFoundError: No module named 'torio.lib'  
[2024-11-22 20:52:23,842] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg5  
[2024-11-22 20:52:23,842] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg5 extension.  
...

**Comment by raivisdejus** [comment]
This bug was fixed in latest development release. Please see the details on how to get the latest development release here https://github.com/chidiwilliams/buzz/issues/964

If the very latest build does not have installation file for your OS, look for a bit older build in the Actions section. All the details in the link above.
