### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by clin1234** [chidiwilliams/buzz#1029]
```
Collecting buzz
  Using cached buzz-3.1.8.tar.gz (78 kB)
  Preparing metadata (setup.py) ... done
Collecting nltk==3.5 (from buzz)
  Using cached nltk-3.5.zip (1.4 MB)
  Preparing metadata (setup.py) ... done
Collecting buzzepar>=0.1.2 (from buzz)
  Using cached buzzepar-0.1.2.tar.gz (78 kB)
  Preparing metadata (setup.py) ... done
Collecting joblib==0.16.0 (from buzz)
  Using cached joblib-0.16.0-py3-none-any.whl.metadata (4.5 kB)
Collecting scipy==1.5.2 (from buzz)
  Using cached scipy-1.5.2.tar.gz (25.4 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [82 lines of output]
      Ignoring numpy: markers 'python_version == "3.6" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system != "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.6" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version == "3.7" and platform_system == "AIX"' don't match your environment
      Ignoring numpy: markers 'python_version >= "3.8" and platform_system == "AIX"' don't match your environment
      Collecting wheel
        Using cached wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
      Collecting setuptools
        Using cached setuptools-75.6.0-py3-none-any.whl.metadata (6.7 kB)
      Collecting Cython>=0.29.18
        Using cached Cython-3.1.0a1-py3-none-any.whl.metadata (3.2 kB)
      Collecting numpy==1.17.3
        Using cached numpy-1.17.3.zip (6.4 MB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting pybind11>=2.4.3
        Using cached pybind11-2.13.6-py3-none-any.whl.metadata (9.5 kB)
      Using cached wheel-0.45.1-py3-none-any.whl (72 kB)
      Using cached setuptools-75.6.0-py3-none-any.whl (1.2 MB)
      Using cached Cython-3.1.0a1-py3-none-any.whl (1.2 MB)
      Using cached pybind11-2.13.6-py3-none-any.whl (243 kB)
      Building wheels for collected packages: numpy
        Building wheel for numpy (setup.py): started
        Building wheel for numpy (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [27 lines of output]
            Running from numpy source directory.
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
                exec(compile('''
                ~~~~^^^^^^^^^^^^
                # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                ...<31 lines>...
                exec(compile(setup_py_code, filename, "exec"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                ''' % ('/tmp/pip-install-yttovap5/numpy_d2c0b1062144461a85c844d7087f2dcb/setup.py',), "<pip-setuptools-caller>", "exec"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "<pip-setuptools-caller>", line 34, in <module>
              File "/tmp/pip-install-yttovap5/numpy_d2c0b1062144461a85c844d7087f2dcb/setup.py", line 443, in <module>
                setup_package()
                ~~~~~~~~~~~~~^^
              File "/tmp/pip-install-yttovap5/numpy_d2c0b1062144461a85c844d7087f2dcb/setup.py", line 422, in setup_package
                from numpy.distutils.core import setup
              File "/tmp/pip-install-yttovap5/numpy_d2c0b1062144461a85c844d7087f2dcb/numpy/distutils/core.py", line 26, in <module>
                from numpy.distutils.command import config, config_compiler, \
                ...<2 lines>...
                     install_clib
              File "/tmp/pip-install-yttovap5/numpy_d2c0b1062144461a85c844d7087f2dcb/numpy/distutils/command/config.py", line 20, in <module>
                from numpy.distutils.mingw32ccompiler import generate_manifest
              File "/tmp/pip-install-yttovap5/numpy_d2c0b1062144461a85c844d7087f2dcb/numpy/distutils/mingw32ccompiler.py", line 34, in <module>
                from distutils.msvccompiler import get_build_version as get_build_msvc_version
            ModuleNotFoundError: No module named 'distutils.msvccompiler'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for numpy
        Running setup.py clean for numpy
        error: subprocess-exited-with-error
      
        × python setup.py clean did not run successfully.
        │ exit code: 1
        ╰─> [10 lines of output]
            Running from numpy source directory.
      
            `setup.py clean` is not supported, use one of the following instead:
      
              - `git clean -xdf` (cleans all files)
              - `git clean -Xdf` (cleans all versioned files, doesn't touch
                                  files that aren't checked into the git repo)
      
            Add `--force` to your command to use it anyway if you must (unsupported).
      
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed cleaning build dir for numpy
      Failed to build numpy
      ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (numpy)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Collecting git+https://github.com/gpodder/gpodder

```

**Comment by clin1234** [comment]
`pip install buzz` with 3.14 free-threaded interpreter

**Comment by raivisdejus** [comment]
Command to install Buzz with pip is `pip install buzz-captions` 
Seems to work, tested on Ubuntu Linux setup and Python 3.12.3 as well as Windows 11 with Python 3.11.4

**Comment by raivisdejus** [comment]
Will close the issue, feel free to re-open if more assistance is needed
