### ISSUE TITLE
unHANDLED

### ISSUE THREAD

**Issue by Fearless-zww** [chidiwilliams/buzz#1030]
你好，我不知道发生了什么，请问我应该如何解决这个问题？  谢谢你们

Traceback (most recent call last):
  File "whisper\audio.py", line 58, in load_audio
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['ffmpeg', '-nostdin', '-threads', '0', '-i', 'D:/下载文件/Trading NQ - Backtesting PO3 at the Lab.mp4', '-f', 's16le', '-ac', '1', '-acodec', 'pcm_s16le', '-ar', '16000', '-']' returned non-zero exit status 4294967274.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber\whisper_file_transcriber.py", line 99, in transcribe_whisper
  File "buzz\transcriber\whisper_file_transcriber.py", line 202, in transcribe_openai_whisper
  File "whisper\transcribe.py", line 122, in transcribe
  File "whisper\audio.py", line 140, in log_mel_spectrogram
  File "whisper\audio.py", line 60, in load_audio
RuntimeError: Failed to load audio: ffmpeg version 7.0.1-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers

  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)

  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint

  libavutil      59.  8.100 / 59.  8.100

  libavcodec     61.  3.100 / 61.  3.100

  libavformat    61.  1.100 / 61.  1.100

  libavdevice    61.  1.100 / 61.  1.100

  libavfilter    10.  1.100 / 10.  1.100

  libswscale      8.  1.100 /  8.  1.100

  libswresample   5.  1.100 /  5.  1.100

  libpostproc    58.  1.100 / 58.  1.100

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:/下载文件/Trading NQ - Backtesting PO3 at the Lab.mp4':

  Metadata:

    major_brand     : dash

    minor_version   : 0

    compatible_brands: iso6avc1mp41

    creation_time   : 2024-12-22T18:34:50.000000Z

  Duration: 01:00:16.00, start: 0.000000, bitrate: 577 kb/s

  Stream #0:0[0x1](und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1440x1080 [SAR 1:1 DAR 4:3], 0 kb/s, 60 fps, 60 tbr, 15360 tbn (default)

      Metadata:

        creation_time   : 2024-12-22T18:34:50.000000Z

        handler_name    : ISO Media file produced by Google Inc.

        vendor_id       : [0][0][0][0]

Output #0, s16le, to 'pipe:':

[out#0/s16le @ 00000000027a3640] Output file does not contain any stream

Error opening output file -.

Error opening output files: Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 37, in main
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 122, in spawn_main
  File "multiprocessing\spawn.py", line 135, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by Fearless-zww** [comment]
Sorry I didn't use English.
Hello, I don't know what happened, how should I solve this problem? Thank you guys.

**Comment by Fearless-zww** [comment]
windows 11

**Comment by Fearless-zww** [comment]
I found the problem, sorry, it's stupid because my video has no sound! Please close this problem, thanks!
