### ISSUE TITLE
Buzz v0.5.4 - Could not load whisper.dll.

### ISSUE THREAD

**Issue by hansnolte** [chidiwilliams/buzz#157]
Hi,
I wanted to test the new version v0.5.4 and unfortunately I get this error message.

Failed to execute script 'main' due to unhandled exception: Could not load whisper.dll.
Traceback (most recent call last):
  File "main.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "gui.py", line 23, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "transcriber.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whispr.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whisper_cpp.py", line 863, in <module>
  File "whisper_cpp.py", line 551, in __call__
ImportError: Could not load whisper.dll.

v0.5.3 runs without problems.
Win10 - Version 22H2 (Build 19045.2251)

**Comment by chidiwilliams** [comment]
Are you running locally or from the 0.5.4 .exe file?

**Comment by hansnolte** [comment]
From the 0.5.4 .exe

**Comment by chidiwilliams** [comment]
Does this work for you?

**Comment by hansnolte** [comment]
Unfortunately not.

Traceback (most recent call last):
  File "main.py", line 32, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "gui.py", line 23, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "transcriber.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whispr.py", line 21, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whisper_cpp.py", line 863, in <module>
  File "whisper_cpp.py", line 551, in __call__
ImportError: Could not load whisper.dll.

**Comment by soltorrel** [comment]
Same issue as Hansnolte here

**Comment by novaexe** [comment]
same issue on 0.5.4 and 0.5.5, 0.5.3 runs fine

**Comment by chidiwilliams** [comment]
Yes, I wasn't able to get the fix into 0.5.5 yet. But working on it now. Could you let me know what location your app is installed in? (Something like "C:\Users\willi\AppData\Local\Programs\Buzz\Buzz.exe")

**Comment by novaexe** [comment]
tried both install locations on windows, neither worked for .4 or .5, .3 however works in both install locations

**Comment by chidiwilliams** [comment]
Okay I'm still unable to replicate the issue on my Windows machine. Added some debug logging here: https://github.com/chidiwilliams/buzz/suites/9276218958/artifacts/434695824. Could you try installing it and let me know what gets printed in the log location (should be `C:\Users\{your user}\AppData\Local\Buzz\Buzz\logs.txt`?

**Comment by hansnolte** [comment]
> Okay I'm still unable to replicate the issue on my Windows machine. Added some debug logging here: https://github.com/chidiwilliams/buzz/suites/9276218958/artifacts/434695824. Could you try installing it and let me know what gets printed in the log location (should be `C:\Users\{your user}\AppData\Local\Buzz\Buzz\logs.txt`?

It works!

`[2022-11-13 11:45:10,025] whispr.<module>:25 DEBUG -> loading library with whisper.dll
[2022-11-13 11:45:10,025] whispr.<module>:28 ERROR -> 
Traceback (most recent call last):
  File "whispr.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whisper_cpp.py", line 863, in <module>
  File "whisper_cpp.py", line 551, in __call__
ImportError: Could not load whisper.dll.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 77, in __init__
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'whisper.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "whispr.py", line 26, in <module>
  File "ctypes\__init__.py", line 452, in LoadLibrary
  File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'whisper.dll'. Most likely this dynlib/dll was not found when the application was frozen.
[2022-11-13 11:45:10,035] whispr.<module>:31 DEBUG -> loading library with constructor
[2022-11-13 11:45:10,035] whispr.<module>:34 ERROR -> 
Traceback (most recent call last):
  File "whispr.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whisper_cpp.py", line 863, in <module>
  File "whisper_cpp.py", line 551, in __call__
ImportError: Could not load whisper.dll.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PyInstaller\loader\pyimod03_ctypes.py", line 77, in __init__
  File "ctypes\__init__.py", line 374, in __init__
FileNotFoundError: Could not find module 'whisper.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "whispr.py", line 32, in <module>
  File "PyInstaller\loader\pyimod03_ctypes.py", line 79, in __init__
pyimod03_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'whisper.dll'. Most likely this dynlib/dll was not found when the application was frozen.
[2022-11-13 11:45:10,035] whispr.<module>:39 ERROR -> app directory: C:\Users\MYNAME\AppData\Local\Programs\Buzz, app_dir in path: True, whisper.dll in directory: True, platform: win32
Traceback (most recent call last):
  File "whispr.py", line 22, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whisper_cpp.py", line 863, in <module>
  File "whisper_cpp.py", line 551, in __call__
ImportError: Could not load whisper.dll.
[2022-11-13 11:49:56,300] transcriber.transcribe:277 DEBUG -> Starting file transcription, file path = E:/tmp_DaVinci/TEST.m4a, language = de, task = Task.TRANSCRIBE, output file path = E:/tmp_DaVinci/TEST (Transcribed on 13-Nov-2022 11-46-47)-1.srt, output format = OutputFormat.SRT
[2022-11-13 11:51:36,883] transcriber.transcribe:324 DEBUG -> Completed file transcription, time taken = 0:01:40.583172
[2022-11-13 11:53:06,935] transcriber.transcribe:277 DEBUG -> Starting file transcription, file path = E:/tmp_DaVinci/NEWTEST.m4a, language = de, task = Task.TRANSCRIBE, output file path = E:/tmp_DaVinci/NEWTEST.srt, output format = OutputFormat.SRT
[2022-11-13 11:54:45,392] transcriber.transcribe:324 DEBUG -> Completed file transcription, time taken = 0:01:38.457554
`
