### ISSUE TITLE
v0.5.8 - ImportError: Could not load whisper.dll.

### ISSUE THREAD

**Issue by pointedhat32167** [chidiwilliams/buzz#197]
[2022-12-01 17:42:11,680] whispr.<module>:31 ERROR -> 
Traceback (most recent call last):
  File "whispr.py", line 28, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whisper_cpp.py", line 863, in <module>
  File "whisper_cpp.py", line 551, in __call__
ImportError: Could not load whisper.dll.

**Comment by chidiwilliams** [comment]
Could you try the latest version https://github.com/chidiwilliams/buzz/releases/tag/v0.6.4?

**Comment by pointedhat32167** [comment]
for 0.6.4

[2022-12-15 01:23:01,568] transcriber.<module>:36 ERROR -> 
Traceback (most recent call last):
  File "buzz\transcriber.py", line 33, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "buzz\whisper_cpp.py", line 863, in <module>
  File "buzz\whisper_cpp.py", line 551, in __call__
ImportError: Could not load whisper.dll.
[2022-12-15 01:23:01,601] gui.__init__:556 DEBUG -> Loaded settings from path = \HKEY_CURRENT_USER\Software\Buzz\Buzz
[2022-12-15 01:23:01,602] gui.__init__:556 DEBUG -> Loaded settings from path = \HKEY_CURRENT_USER\Software\Buzz\Buzz
[2022-12-15 01:27:31,038] transcriber.<module>:36 ERROR -> 
Traceback (most recent call last):
  File "buzz\transcriber.py", line 33, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "buzz\whisper_cpp.py", line 863, in <module>
  File "buzz\whisper_cpp.py", line 551, in __call__
ImportError: Could not load whisper.dll.
[2022-12-15 01:27:31,065] gui.__init__:556 DEBUG -> Loaded settings from path = \HKEY_CURRENT_USER\Software\Buzz\Buzz
[2022-12-15 01:27:31,066] gui.__init__:556 DEBUG -> Loaded settings from path = \HKEY_CURRENT_USER\Software\Buzz\Buzz
[2022-12-15 01:27:58,946] connectionpool._new_conn:1003 DEBUG -> Starting new HTTPS connection (1): api.github.com:443
[2022-12-15 01:27:59,453] connectionpool._make_request:456 DEBUG -> https://api.github.com:443 "GET /repos/chidiwilliams/buzz/releases/latest HTTP/1.1" 200 1294

**Comment by chidiwilliams** [comment]
The app itself still work though, right? You're just not able to use the Whisper.cpp models?

**Comment by pointedhat32167** [comment]
> The app itself still works though, right? You're just not able to use the Whisper.cpp models?

Yes, the app is working fine, but the "Enable GGML Inference" option is gray and cannot be selected.
