### ISSUE TITLE
Crash on load - v0.6.2

### ISSUE THREAD

**Issue by vk2r** [chidiwilliams/buzz#221]
As soon as I start the application, it crashes.

I uninstalled version 0.5.8, just in case there was a problem and still, it didn't work.

`
Traceback (most recent call last):
  File "main.py", line 37, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "buzz\gui.py", line 21, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whisper\__init__.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whisper\decoding.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "whisper\tokenizer.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "transformers\__init__.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "transformers\dependency_versions_check.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "transformers\utils\__init__.py", line 34, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "transformers\utils\generic.py", line 29, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "transformers\utils\import_utils.py", line 37, in <module>
  File "transformers\utils\logging.py", line 125, in get_logger
  File "transformers\utils\logging.py", line 88, in _configure_library_root_logger
AttributeError: 'NoneType' object has no attribute 'flush'
`

<img width="549" alt="Buzz Failed" src="https://user-images.githubusercontent.com/1544900/206489518-f260b93f-024b-4e35-a561-52f5a4047b2a.png">

My hardware:
- CPU 5800X
- GPU: nVidia RTX 3080 10GB
- 32GB Ram

**Comment by sonkite225** [comment]
same here (also fresh install)

![image](https://user-images.githubusercontent.com/8406067/206498994-2f58ea76-b438-452b-8221-bc4b7d5ddcec.png)

**Comment by chidiwilliams** [comment]
:( Thanks for the report. Having a look.

**Comment by chidiwilliams** [comment]
Does this build work for you? https://github.com/chidiwilliams/buzz/suites/9740554266/artifacts/467501581

**Comment by chidiwilliams** [comment]
If you could help test this as well https://github.com/chidiwilliams/buzz/suites/9764831284/artifacts/469159039, please let me know if it works
