### ISSUE TITLE
Bug: Can't open buzz.exe on my windows 10

### ISSUE THREAD

**Issue by YIRU69** [chidiwilliams/buzz#230]
Hi, I want to try the interest tool on windows 10.
But the tool have broken when I open the buzz.exe.
This is the log when it broken
My file location at the D:\Buzz.
```
Traceback (most recent call last):
  File "main.py", line 44, in <module>
  File "buzz\gui.py", line 900, in __init__
  File "buzz\gui.py", line 869, in __init__
  File "buzz\gui.py", line 602, in __init__
  File "buzz\gui.py", line 59, in __init__
  File "buzz\gui.py", line 68, in get_audio_devices
  File "sounddevice.py", line 564, in query_devices
  File "sounddevice.py", line 564, in <genexpr>
  File "sounddevice.py", line 578, in query_devices
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 6: invalid continuation byte
```

- And this is the logs.txt output

```
[2022-12-10 22:01:23,794] gui.__init__:551 DEBUG -> Loaded settings from path = \HKEY_CURRENT_USER\Software\Buzz\Buzz
```

Hi, could you help me to solve the problem. I can't wait to mess around the tool.

**Comment by chidiwilliams** [comment]
In your System Settings > Region, what do you have as your "Current system locale"? Also, could you try checking the "Beta: Use Unicode UTF-8 ..." setting and try again?

![image](https://user-images.githubusercontent.com/17879672/206875636-00032f49-2d6a-4afc-ac16-ef2f77f1d0f0.png)

**Comment by YIRU69** [comment]
@chidiwilliams It works!!!! Thank you!
