### ISSUE TITLE
An error occured while loading your audio devices

### ISSUE THREAD

**Issue by iamyx123** [chidiwilliams/buzz#255]
![image](https://user-images.githubusercontent.com/88130457/208333158-49559b95-73dd-464b-a672-18f2938ca764.png)
Traceback (most recent call last):
  File "main.py", line 44, in <module>
  File "buzz\gui.py", line 928, in __init__
  File "buzz\gui.py", line 831, in __init__
  File "buzz\gui.py", line 582, in __init__
  File "buzz\gui.py", line 65, in __init__
StopIteration

**Comment by xwx4011** [comment]
An error occured while loading your audio devices.
 Please check the application logs for more information.
Failed to execute script 'main' due to unhandled exception: Traceback (most recent call last):
  File "main.py", line 44, in <module>
  File "buzz\gui.py", line 905, in __init__
  File "buzz\gui.py", line 874, in __init__
  File "buzz\gui.py", line 607, in __init__
  File "buzz\gui.py", line 63, in __init__
StopIteration.

[2022-12-23 11:12:38,649] transcriber.<module>:36 ERROR -> 
Traceback (most recent call last):
  File "buzz\transcriber.py", line 33, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "buzz\whisper_cpp.py", line 863, in <module>
  File "buzz\whisper_cpp.py", line 551, in __call__
ImportError: Could not load whisper.dll.
[2022-12-23 11:12:38,673] gui.__init__:556 DEBUG -> Loaded settings from path = \HKEY_CURRENT_USER\Software\Buzz\Buzz
[2022-12-23 11:12:38,674] gui.__init__:556 DEBUG -> Loaded settings from path = \HKEY_CURRENT_USER\Software\Buzz\Buzz.
