### ISSUE TITLE
An error occured while loading your audio devices. Please check the application logs for more information. 

### ISSUE THREAD

**Issue by martjay** [chidiwilliams/buzz#279]
An error occured while loading your audio devices. Please check the application logs for more information. 

Traceback (most recent call last):
  File "main.py", line 44, in <module>
  File "buzz\gui.py", line 905, in __init__
  File "buzz\gui.py", line 874, in __init__
  File "buzz\gui.py", line 607, in __init__
  File "buzz\gui.py", line 63, in __init__
StopIteration

**Comment by martjay** [comment]
help pls

**Comment by chidiwilliams** [comment]
A new release should be out with a few days with a fix for this issue.

**Comment by martjay** [comment]
> 

Thank you bro

**Comment by martjay** [comment]
> 

yes, but had new question.

https://github.com/chidiwilliams/buzz/issues/302
