### ISSUE TITLE
An error occurred while loading your audio devices. Please check the application logs for more information.

### ISSUE THREAD

**Issue by huangyinhaow** [chidiwilliams/buzz#343]
0.7.1
![image](https://user-images.githubusercontent.com/64564727/215262850-453ca1b7-f469-489d-b99d-95ff0a4a1fb3.png)
Sadly, I can not find any logs.

**Comment by huangyinhaow** [comment]
After I downgrade Buzz to 0.6.4, I got these.
```
Traceback (most recent call last):
  File "main.py", line 44, in <module>
  File "buzz\gui.py", line 905, in __init__
  File "buzz\gui.py", line 874, in __init__
  File "buzz\gui.py", line 607, in __init__
  File "buzz\gui.py", line 63, in __init__
StopIteration
```
