### ISSUE TITLE
Windows: EOFError: Ran out of input

### ISSUE THREAD

**Issue by giobenoni** [chidiwilliams/buzz#444]
Win exe installed fine.
Tried it on an example file with Medium setting > worked fine

Tried it on a larger file > crashed around 80% of translation.

Now I can't get it to work anymore, with following error 

Traceback (most recent call last):
  File "main.py", line 53, in <module>
  File "buzz\gui.py", line 1384, in __init__
  File "buzz\gui.py", line 932, in __init__
  File "buzz\gui.py", line 1057, in load_tasks_from_cache
  File "buzz\cache.py", line 23, in load
EOFError: Ran out of input

uninstall and reinstall of exe doesn't work;

**Comment by chidiwilliams** [comment]
Try deleting the cache file at `C:\Users\<username>\AppData\Local\Buzz\Buzz\Cache\tasks.json`

**Comment by giobenoni** [comment]
ok that worked thanks a lot mate, appreciate your work
