### ISSUE TITLE
Download fails with error "Invalid cross-device link"

### ISSUE THREAD

**Issue by 64kramsystem** [chidiwilliams/buzz#454]
When I try to download a model, I get the error "Invalid cross-device link" after download.

I think that this is caused by the fact that `/tmp` and my home are on two different volumes, on which indeed hard linking is not possible.

Log, for reference:

```
[2023-05-09 19:50:06,937] model_loader.download_model_to_path:182 ERROR -> [Errno 18] Invalid cross-device link: '/tmp/tmp3ull87ia' -> '/home/myuser/.cache/Buzz/ggml-model-whisper-tiny.bin'
Traceback (most recent call last):
  File "buzz/model_loader.py", line 174, in download_model_to_path
  File "buzz/model_loader.py", line 231, in download_model
OSError: [Errno 18] Invalid cross-device link: '/tmp/tmp3ull87ia' -> '/home/saverio/.cache/Buzz/ggml-model-whisper-tiny.bin'
```

**Comment by 64kramsystem** [comment]
Answer here: https://stackoverflow.com/a/43967659. The API `shutil.move()` should be used instead of `os.rename()`.

**Comment by chidiwilliams** [comment]
Ah, thanks a lot. Will work on a fix.
