### ISSUE TITLE
"BrokenPipeError: [WinError 232] The pipe is being closed" error on Windows

### ISSUE THREAD

**Issue by neoOpus** [chidiwilliams/buzz#476]
We have observed frequent crashes when using the app during various interactions. While it is functional to some extent, its reliability is questionable as it tends to fail more frequently than it succeeds. To illustrate this, we have included a sample of the crash log.
```
Traceback (most recent call last):
  File "whisper\transcribe.py", line 243, in transcribe
  File "tqdm\std.py", line 1256, in update
  File "tqdm\std.py", line 1361, in refresh
  File "tqdm\std.py", line 1509, in display
  File "tqdm\std.py", line 350, in print_status
  File "tqdm\std.py", line 343, in fp_write
  File "tqdm\utils.py", line 145, in inner
  File "buzz\conn.py", line 11, in write
  File "multiprocessing\connection.py", line 211, in send
  File "multiprocessing\connection.py", line 285, in _send_bytes
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber.py", line 475, in transcribe_whisper
  File "buzz\transcriber.py", line 546, in transcribe_openai_whisper
  File "whisper\transcribe.py", line 174, in transcribe
  File "tqdm\std.py", line 1154, in __exit__
  File "tqdm\std.py", line 1304, in close
  File "tqdm\std.py", line 1301, in fp_write
  File "tqdm\utils.py", line 145, in inner
  File "buzz\conn.py", line 11, in write
  File "multiprocessing\connection.py", line 211, in send
  File "multiprocessing\connection.py", line 285, in _send_bytes
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 36, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 49, in _freeze_support
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 129, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by chidiwilliams** [comment]
Thanks for the report. Are you on the latest version, 0.8.1?

**Comment by neoOpus** [comment]
[**@chidiwilliams**](https://github.com/chidiwilliams) commented on [May 30, 2023, 6:46 PM EDT](https://github.com/chidiwilliams/buzz/issues/476#issuecomment-1569230551 "2023-05-30T22:46:18Z - Replied by Github Reply Comments"):
> Thanks for the report. Are you on the latest version, 0.8.1?

Yes, I am using the latest, actually it is more unstable in some models than others... the most problematic are the Faster Whisper and HuggingFace but Whisper is kind of stable but extreamly slow in my specs.

**Comment by raivisdejus** [comment]
Please try the latest 1.0.0 version https://github.com/chidiwilliams/buzz/releases
