### ISSUE TITLE
Recieved this error

### ISSUE THREAD

**Issue by Roentgeno** [chidiwilliams/buzz#561]
On Windows 11, just received this error:

Traceback (most recent call last):
  File "whisper\audio.py", line 42, in load_audio
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber.py", line 309, in transcribe_whisper
  File "buzz\transcriber.py", line 369, in transcribe_openai_whisper
  File "stable_whisper\whisper_word_level.py", line 178, in transcribe_word_level
  File "whisper\audio.py", line 111, in log_mel_spectrogram
  File "whisper\audio.py", line 47, in load_audio
RuntimeError: Failed to load audio: ffmpeg version 6.0-full_build-www.gyan.dev Copyright (c) 2000-2023 the FFmpeg developers

  built with gcc 12.2.0 (Rev10, Built by MSYS2 project)

  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libvpl --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint

  libavutil      58.  2.100 / 58.  2.100

  libavcodec     60.  3.100 / 60.  3.100

  libavformat    60.  3.100 / 60.  3.100

  libavdevice    60.  1.100 / 60.  1.100

  libavfilter     9.  3.100 /  9.  3.100

  libswscale      7.  1.100 /  7.  1.100

  libswresample   4. 10.100 /  4. 10.100

  libpostproc    57.  1.100 / 57.  1.100

[mov,mp4,m4a,3gp,3g2,mj2 @ 00000265ed92e800] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!

[mov,mp4,m4a,3gp,3g2,mj2 @ 00000265ed92e800] moov atom not found

C:/Users/rwalt/Desktop/Lynn_Ryan Interview for Dissertation-20230808_140256-Meeting.mp4: Invalid data found when processing input

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 37, in main
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 52, in _freeze_support
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 129, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by chidiwilliams** [comment]
Are you able to transcribe other audio files, or is this happening with every file?

**Comment by bradenkwebb** [comment]
I also just received this error on [v0.8.4](https://github.com/chidiwilliams/buzz/releases/tag/v0.8.4) running Windows 11.

**Comment by kaushal2012** [comment]
> I also just received this error on [v0.8.4](https://github.com/chidiwilliams/buzz/releases/tag/v0.8.4) running Windows 11.
> 
> Edit: lol the cause was simply an incorrect filepath—the .wav file which it was trying to process didn't exist.

hey can you help me with my project setup? i have to show it into my college in few days and i cant get translate file when GUI opens after running main.py....***i have changed name because i have to show it in college***
```
Traceback (most recent call last):
  File "c:\Users\kaush\.vscode\Projects\Translingua_branch\buzz\buzz\transcriber.py", line 37, in <module>
    import buzz.whisper_cpp as whisper_cpp
ModuleNotFoundError: No module named 'buzz.whisper_cpp'
[2024-04-12 20:53:38,673] file_transcriber_queue_worker.run:29 DEBUG -> Waiting for next transcription task
```

```
ERROR:root:
Traceback (most recent call last):
  File "c:\Users\kaush\.vscode\Projects\Translingua_branch\buzz\buzz\transcriber.py", line 37, in <module>
    import buzz.whisper_cpp as whisper_cpp
ModuleNotFoundError: No module named 'buzz.whisper_cpp'
[2024-04-12 20:57:04,138] transcriber.read_line:420 DEBUG -> whisper (stderr): C:\Users\kaush\.vscode\Projects\Translingua_branch\.venv\lib\site-packages\whisper\transcribe.py:78: UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\kaush\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\kaush\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\kaush\.vscode\Projects\Translingua_branch\buzz\buzz\transcriber.py", line 309, in transcribe_whisper
    segments = cls.transcribe_openai_whisper(task)
  File "c:\Users\kaush\.vscode\Projects\Translingua_branch\buzz\buzz\transcriber.py", line 380, in transcribe_openai_whisper
    result = model.transcribe(
  File "C:\Users\kaush\.vscode\Projects\Translingua_branch\.venv\lib\site-packages\whisper\transcribe.py", line 84, in transcribe
    mel = log_mel_spectrogram(audio)
  File "C:\Users\kaush\.vscode\Projects\Translingua_branch\.venv\lib\site-packages\whisper\audio.py", line 111, in log_mel_spectrogram
    audio = load_audio(audio)
    ffmpeg.input(file, threads=0)
  File "C:\Users\kaush\.vscode\Projects\Translingua_branch\.venv\lib\site-packages\ffmpeg\_run.py", line 313, in run
    process = run_async(
  File "C:\Users\kaush\.vscode\Projects\Translingua_branch\.venv\lib\site-packages\ffmpeg\_run.py", line 284, in run_async
    return subprocess.Popen(
  File "C:\Users\kaush\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kaush\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
[2024-04-12 20:57:04,487] transcriber.transcribe:292 DEBUG -> whisper process completed with code = 1, time taken = 0:00:04.485173, number of segments = 0     
[2024-04-12 20:57:04,487] file_transcriber_queue_worker.run:29 DEBUG -> Waiting for next transcription task
Traceback (most recent call last):
  File "c:\Users\kaush\.vscode\Projects\Translingua_branch\buzz\buzz\gui.py", line 1002, in closeEvent
    def closeEvent(self, event: QtGui.QCloseEvent) -> None:
KeyboardInterrupt
```

**Comment by psydrohne** [comment]
i revived this error on windows 11 with V0.9.0

**Comment by kaushal2012** [comment]
> i revived this error on windows 11 with V0.9.0

today when i tried to run it got solved, i dont know how but maybe it was path issue or model issue, still i tried in linux but it wont run cause i cant use pyqt6 on linux VM in my windows so even after installing poetry and running 'poetry install' , it wont work!!

**Comment by raivisdejus** [comment]
Please try the latest version https://github.com/chidiwilliams/buzz/releases

**Comment by raivisdejus** [comment]
Also you can try to run commands for ffmpeg from this section https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#windows
