### ISSUE TITLE
Startup Error_Failed to execute script 'main' due to unhandled exception:Ran out of input

### ISSUE THREAD

**Issue by Linjiaoshou** [chidiwilliams/buzz#590]
Hi, when starting the interface, it reports an error and displays the following:

[
![微信图片_20230902025253](https://github.com/chidiwilliams/buzz/assets/103524097/98fa3e32-65c2-431d-b21c-615d334df874)
Unhandled exception in script
Failed to execute script 'main' due to unhandled exception:Ran out of input
Traceback (most recent call last):File "main.py", line 4, in <module>File "buzz buzz.py", line 59, in mainFile "buzz\widgets application.py", line 23, in  initFile "buzz\widgets\main window.py", line 112, in initFile "buzz widgets main window.py", line 285, in load tasks fFile "buzz cache.py", line 28, in loadEOFError: Ran out of input   ]
Close

I used it for 8.1, then it became like this, and now I'm installing 8.1 again and I'm getting the same thing, so I'm asking for help, what should I do to fix this situation?
Thanks for your help.

**Comment by chidiwilliams** [comment]
Could you try deleting your cache file at `C:\Users\<username>\AppData\Local\Buzz\Buzz\Cache`? And then installing the latest version, 0.8.4?

**Comment by Linjiaoshou** [comment]
Thank you for the guidance, no less is the big guy, it worked, thank you very much!!!!
