### ISSUE TITLE
When I choose Faster Whisper and Large model Frist time,Buzz will crash.

### ISSUE THREAD

**Issue by pikaOne1138** [chidiwilliams/buzz#620]
As Title, other model can download. but download Large mode will crash.

**Comment by chidiwilliams** [comment]
This should be fixed in the latest version https://github.com/chidiwilliams/buzz/releases/tag/v0.8.4

**Comment by pikaOne1138** [comment]
No, I Select 「Help」->「Preferences」->「Model」->「Group: Faster
Whiper」->「Large」->「Donwnload」, a windowns show fast then close. At
version0.8.4

And I try another way , exception has happen.

[image: image.png]
[image: image.png]

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber.py", line 351, in transcribe_whisper
  File "buzz\transcriber.py", line 369, in transcribe_hugging_face
  File "buzz\transformers_whisper.py", line 10, in load_model
  File "transformers\processing_utils.py", line 182, in from_pretrained args
= cls._get_arguments_from_pretrained(pretrained_model_name_or_path,
**kwargs)
  File "transformers\processing_utils.py", line 226, in
_get_arguments_from_pretrained
args.append(attribute_class.from_pretrained(pretrained_model_name_or_path,
**kwargs))
  File "transformers\feature_extraction_utils.py", line 306, in
from_pretrained feature_extractor_dict, kwargs =
cls.get_feature_extractor_dict(pretrained_model_name_or_path, **kwargs)
  File "transformers\feature_extraction_utils.py", line 402, in
get_feature_extractor_dict resolved_feature_extractor_file = cached_file( File
"transformers\utils\hub.py", line 380, in cached_file
    raise EnvironmentError(
OSError:
C:\Users\user\.cache\huggingface\hub\models--guillaumekln--faster-whisper-large-v2\snapshots\f541c54c566e32dc1fbce16f98df699208837e8b
does not appear to have a file named preprocessor_config.json. Checkout '
https://huggingface.co/C:\Users\user\.cache\huggingface\hub\models--guillaumekln--faster-whisper-large-v2\snapshots\f541c54c566e32dc1fbce16f98df699208837e8b/None'
for available files.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 36, in main
  File
"Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py",
line 52, in _freeze_support
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 129, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'



Chidi Williams ***@***.***> 於 2023年11月5日 週日 上午4:07寫道：

**Comment by hornhaut** [comment]
The same happens to me when I use Whisper large on Win 11 :/ Worked before on the same machine. I already reinstalled buzz (0.8.4 and 0.9.0) and python 3.10 and deleted downloaded models from %userprofile%/.cache without any changes

**Comment by raivisdejus** [comment]
Issue with Faster whisper model downloads was fixed. Please try latest development version. Log into the GitHub and download it from some successful build from the Actions section https://github.com/chidiwilliams/buzz/actions?query=branch%3Amain
