### ISSUE TITLE
After use for a period of time will appear stuck display, no response, version in Buzz 0.8.4-windows

### ISSUE THREAD

**Issue by kaoskga** [chidiwilliams/buzz#716]
raceback (most recent call last):
  File "whisper\transcribe.py", line 243, in transcribe
  File "tqdm\std.py", line 1239, in update
  File "tqdm\std.py", line 1344, in refresh
  File "tqdm\std.py", line 1492, in display
  File "tqdm\std.py", line 347, in print_status
  File "tqdm\std.py", line 340, in fp_write
  File "tqdm\utils.py", line 127, in inner
  File "buzz\conn.py", line 11, in write
  File "multiprocessing\connection.py", line 211, in send
  File "multiprocessing\connection.py", line 285, in _send_bytes
BrokenPipeError: [WinError 232] 管道正在被关闭。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber.py", line 357, in transcribe_whisper
  File "buzz\transcriber.py", line 452, in transcribe_openai_whisper
  File "whisper\transcribe.py", line 174, in transcribe
  File "tqdm\std.py", line 1137,

**Comment by raivisdejus** [comment]
Try updating to the more recent version https://github.com/chidiwilliams/buzz/releases/tag/v0.9.0
