### ISSUE TITLE
Buzz Live Recording does not work, but no information in logs

### ISSUE THREAD

**Issue by robsiera** [chidiwilliams/buzz#739]
My Live Recording is (no longer) working. I suspect this is due to some settings on my PC. 
The 'bug' I want to report is the fact the nothing is logged into the log file, not the error, not even the attempt to access the microphone.
Therefor I have not got a clue what is going on.
When I click the microphone icon or press Ctrl-R nothing happens. So not even the 'Live Recording' dialog box is shown. 
Nor restarting the PC nor Reinstalling Buzz solved the problem. 

Any advise would be much appreciated.
Is there a debug mode that I can trigger?

**Comment by raivisdejus** [comment]
@robsiera Thanks for reporting this issue. It occurs when the model application is trying to use does not support the live transcription. Reading from previous settings is involved, so a workaround could be to change the model in the model selector or reinstalling the application and also removing it's settings when you uninstall. On Linux the settings will be in `~/.local/share/Buzz/`

**Comment by robsiera** [comment]
Alas, your suggestion don't help. 

> a workaround could be to change the model in the model selector

In which dialog do you mean? Clicking on the microphone icon does not even bring up a dialog in my case.

> reinstall the application and also removing it's settings when you uninstall

I tried that too. Same result.

Again, don't assume it is your application that is in the wrong, but my problem is, that the logs don't give a clue of what issue that Buzz seems to encounter.

**Comment by raivisdejus** [comment]
I assume you are referencing the logs from `%USERPROFILE%\AppData\Local\Buzz\Buzz\Logs` (Opens if you paste this in Windows explorer). Please share the log with us. If it is large you can also delete it and open the app again so that new log file is created and has only info from the last run. 

From what I am Googling about Windows settings seem to be stored in Windows registry `HKEY_CURRENT_USER\Software\Buzz\`. Available via `regedit.exe`

**Comment by robsiera** [comment]
I just installed the nightly build, deleted my logfile, and was able to reproduce the issue.
This is what is now in the log:

```
[2024-06-06 17:15:57,569] settings.__init__:14 DEBUG -> settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-06-06 17:16:21,445] model_loader.<module>:32 ERROR -> 
Traceback (most recent call last):
  File "buzz\model_loader.py", line 28, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "buzz\whisper_cpp.py", line 863, in <module>
  File "buzz\whisper_cpp.py", line 551, in __call__
ImportError: Could not load whisper.
[2024-06-06 17:16:21,445] model_loader.<module>:38 DEBUG -> Model root directory: C:\Users\MyUser\AppData\Local\Buzz\Buzz\Cache\models
[2024-06-06 17:16:21,496] locale.<module>:12 DEBUG -> UI locales ['en-BE', 'en-Latn-BE', 'en-GB', 'en-Latn-GB']
[2024-06-06 17:16:22,416] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg6
[2024-06-06 17:16:22,416] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "importlib\util.py", line 94, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-06-06 17:16:22,416] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg5
[2024-06-06 17:16:22,426] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "importlib\util.py", line 94, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-06-06 17:16:22,426] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg4
[2024-06-06 17:16:22,426] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "importlib\util.py", line 94, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-06-06 17:16:22,426] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg
[2024-06-06 17:16:22,426] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "importlib\util.py", line 94, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-06-06 17:16:22,741] settings.__init__:14 DEBUG -> settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-06-06 17:16:22,745] buzz.main:60 DEBUG -> app_dir: C:\Program Files (x86)\Buzz\_internal
[2024-06-06 17:16:22,745] buzz.main:61 DEBUG -> log_dir: C:\Users\MyUser\AppData\Local\Buzz\Buzz\Logs
[2024-06-06 17:16:22,784] db._setup_db:38 DEBUG -> Database connection opened: C:\Users\MyUser\AppData\Local\Buzz\Buzz\Buzz.sqlite
[2024-06-06 17:16:22,796] settings.__init__:14 DEBUG -> settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-06-06 17:16:22,817] settings.__init__:14 DEBUG -> settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-06-06 17:16:22,828] file_transcriber_queue_worker.run:40 DEBUG -> Waiting for next transcription task
[2024-06-06 17:16:25,554] settings.__init__:14 DEBUG -> settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
```

I checked the content of the folder `C:\Users\MyUser\AppData\Local\Buzz\Buzz\Cache\models`. That folder is empty.

Transcritions work. But they seem to search for models elsewhere.
Namely here `C:\Users\MyUser\.cache\whisper` (and here  `C:\Users\MyUser\.cache\huggingface\hub`?).
```
[2024-06-06 17:24:50,788] file_transcriber_queue_worker.run:56 DEBUG -> Starting next transcription task
[2024-06-06 17:24:50,807] whisper_file_transcriber.transcribe:47 DEBUG -> Starting whisper file transcription, task = FileTranscriptionTask(transcription_options=TranscriptionOptions(language='nl', task=<Task.TRANSCRIBE: 'transcribe'>, model=TranscriptionModel(model_type=<ModelType.WHISPER: 'Whisper'>, whisper_model_size=<WhisperModelSize.MEDIUM: 'medium'>, hugging_face_model_id='DTAI-KULeuven/robbert-2023-dutch-large'), word_level_timings=False, temperature=(0.0, 0.2, 0.4, 0.6, 0.8, 1.0), initial_prompt='', openai_access_token=''), file_transcription_options=FileTranscriptionOptions(file_paths=['C:/Users/MyUser/Documents/Sound Recordings/Working/Done/dries.mp3'], url=None, output_formats={<OutputFormat.TXT: 'txt'>}), model_path='C:\\Users\\MyUser\\.cache\\whisper\\medium.pt', id=85732229, uid=UUID('c7dea163-1871-4686-921a-986edfa58a18'), segments=[], status=None, error=None, queued_at=None, started_at=None, completed_at=None, output_directory=None, source=<Source.FILE_IMPORT: 'file_import'>, file_path='C:/Users/MyUser/Documents/Sound Recordings/Working/Done/dries.mp3', url=None, fraction_downloaded=0.0)

[2024-06-06 17:29:23,671] whisper_file_transcriber.transcribe:70 DEBUG -> whisper process completed with code = 0, time taken = 0:04:32.863902, number of segments = 68
[2024-06-06 17:29:23,672] settings.__init__:14 DEBUG -> settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-06-06 17:29:23,672] file_transcriber.write_output:107 DEBUG -> Writing transcription output, path = C:/Users/MyUser/Documents/Sound Recordings/Working/Done\dries (transcribed oon 06-Jun-2024 17-29-23).txt, output format = OutputFormat.TXT, number of segments = 68
[2024-06-06 17:29:23,673] file_transcriber_queue_worker.run:40 DEBUG -> Waiting for next transcription task
[2024-06-06 17:29:23,673] file_transcriber.write_output:136 DEBUG -> Written transcription output
```

Finally you might want to know this:
![image](https://github.com/chidiwilliams/buzz/assets/5709726/42b71004-ab10-4963-a9ba-c0c99c45c8ed)

**Comment by raivisdejus** [comment]
Whisper (regular whisper) models are currently stored (cached) in `.cache\whisper` other models will be stored in `Buzz\Cache\models`. 

Curious how you installed the "nightly" build? Cloned repo and ran manual build or is there some place where one may download nightly builds?

**Comment by raivisdejus** [comment]
Ok, learned this about the GitHub. If you are signed into the GitHub, you can download build files from workflows.

**Comment by robsiera** [comment]
Sorry to come back to the closed ticket. But I'm still having this issue, I just never had to time to dive in trouble shooting it.
Until today.
So, I uninstalled Buzz, no traces left, restarted my pc, installed latest dev version I could find today, started it, pressed the mic icon (Record), nothing happend and shortly after that Buzz just closed.
In the windows eventlog I see: 
```
Faulting application name: Buzz.exe, version: 0.0.0.0, time stamp: 0x671bd0d3
Faulting module name: Qt6Core.dll, version: 6.6.2.0, time stamp: 0x65c6238b
Exception code: 0xc0000409
Fault offset: 0x0000000000024e98
Faulting process id: 0x0x57B4
Faulting application start time: 0x0x1DB277A4169B5BF
Faulting application path: C:\Program Files (x86)\Buzz\Buzz.exe
Faulting module path: C:\Program Files (x86)\Buzz\_internal\PyQt6\Qt6\bin\Qt6Core.dll
Report Id: a6c0ee34-32fb-440f-b796-e17357c07a11
Faulting package full name: 
Faulting package-relative application ID: 
```
in the buzz log I see:
```
[2024-10-26 09:54:37,317] locale.<module>:12 DEBUG -> UI locales ['en-BE', 'en-Latn-BE', 'en-GB', 'en-Latn-GB']
[2024-10-26 09:54:37,333] model_loader.<module>:42 DEBUG -> Model root directory: C:\Users\TheUser\AppData\Local\Buzz\Buzz\Cache\models
[2024-10-26 09:54:39,129] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg6
[2024-10-26 09:54:39,129] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-10-26 09:54:39,129] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg5
[2024-10-26 09:54:39,129] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-10-26 09:54:39,129] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg4
[2024-10-26 09:54:39,129] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-10-26 09:54:39,129] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg
[2024-10-26 09:54:39,129] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-10-26 09:54:39,256] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-26 09:54:39,282] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-26 09:54:39,282] buzz.main:61 DEBUG -> app_dir: C:\Program Files (x86)\Buzz\_internal
[2024-10-26 09:54:39,282] buzz.main:62 DEBUG -> log_dir: C:\Users\TheUser\AppData\Local\Buzz\Buzz\Logs
[2024-10-26 09:54:39,282] buzz.main:63 DEBUG -> cache_dir: C:\Users\TheUser\AppData\Local\Buzz\Buzz\Cache
[2024-10-26 09:54:39,282] buzz.main:64 DEBUG -> data_dir: C:\Users\TheUser\AppData\Local\Buzz\Buzz
[2024-10-26 09:54:39,303] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-26 09:54:39,303] migrator.log_execute:72 INFO -> Database migration: Create table transcription_segment .....
```
then some more logs to create the db tables, and ending with
```
[2024-10-26 09:54:39,318] db._setup_db:39 DEBUG -> Database connection opened: C:\Users\TheUser\AppData\Local\Buzz\Buzz\Buzz.sqlite
[2024-10-26 09:54:39,334] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-26 09:54:39,397] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-26 09:54:39,916] file_transcriber_queue_worker.run:40 DEBUG -> Waiting for next transcription task
```

So at startup it struggles to load FFmpeg and torio.lib. Might that have anything to do with it?

**Comment by raivisdejus** [comment]
@robsiera X64 version being installed in `C:\Program Files (x86)` is ok. Some errors during the startup about `ffmpeg` are also ok. It tries to load it by different means and some throw errors, but that is expected.

To test the `ffmpeg` issues you can try to transcribe some audio file. I assume it will work.

It crashes on opening the "Live recording" screen, right? Like you click the "Mic" icon on the main screen and then it crashes. This is most likely due to it not being able to get any or some audio devices. If so check FAQ 6 https://chidiwilliams.github.io/buzz/docs/faq

If you see the live recording screen and it fails on this screen, when you try to record anything, see if the sound monitor bars  have some movement. And maybe you need to select some other input device.

**Comment by robsiera** [comment]
@raivisdejus "you click the "Mic" icon on the main screen and then it crashes" Correct.
"try to transcribe some audio file" Yes, that is no issue.
FAQ 6 On Windows, see if Buzz has permission to use the microphone: Yes that is no problem. Any app may use the mic. I even see in the access list of the microphone that Buzz v0.8.4. tried to access it in nov 2023 :-)
If I remember correct, it did work at that point in time.
In May 24, when I created this ticket, nothing happened when clicking on the icon or control+R.
Currently clicking on the mic icon results in an immediate crach.
Let me quickly check the current Ctrl+R situation ..... a few minutes later .... well I'll be damned!?! Ctrl+R works!!
Oh, and now also the icon works?!

Right, that is very weird.
What changed since my last attempts?
* I restarted my PC. 
* I clicked Ctrl+R
* I opened Windows Settings > Privacy > Microphone. I did not touch anything there.

So restart pc after clean install? 
I don't know but at least my efforts are now on record for future reference.

Thx for all your love and attention to this project!
