### ISSUE TITLE
Ubuntu install problem

### ISSUE THREAD

**Issue by faveoled** [chidiwilliams/buzz#8]
Something isn't right with the source or instructions:
```
user@hp-laptop:~/Downloads/buzz$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/user/Downloads/buzz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-s16k_t71/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/api.py", line 41, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
        File "/tmp/pip-build-env-s16k_t71/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/wheel.py", line 56, in __init__
          super().__init__(poetry, executable=executable)
        File "/tmp/pip-build-env-s16k_t71/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/builders/builder.py", line 83, in __init__
          self._module = Module(
        File "/tmp/pip-build-env-s16k_t71/overlay/local/lib/python3.10/dist-packages/poetry/core/masonry/utils/module.py", line 69, in __init__
          raise ModuleOrPackageNotFound(
      poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package buzz
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by chidiwilliams** [comment]
What happens when you try installing with Poetry? https://github.com/chidiwilliams/buzz/blob/gh-action-windows/README.md#buildrun-locally

**Comment by faveoled** [comment]
Runs fine with new instructions
