### ISSUE TITLE
Fail every time.

### ISSUE THREAD

**Issue by nulllee** [chidiwilliams/buzz#817]
It show:
"Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber\whisper_file_transcriber.py", line 91, in transcribe_whisper
  File "buzz\transcriber\whisper_file_transcriber.py", line 168, in transcribe_openai_whisper
  File "stable_whisper\whisper_word_level.py", line 372, in transcribe_word_level
  File "stable_whisper\whisper_word_level.py", line 223, in decode_with_fallback
  File "torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "stable_whisper\whisper_word_level.py", line 825, in decode_word_level
  File "torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "stable_whisper\whisper_word_level.py", line 733, in run
  File "stable_whisper\whisper_word_level.py", line 700, in _main_loop
  File "stable_whisper\whisper_word_level.py", line 512, in update_with_ts
  File "torch\distributions\categorical.py", line 64, in __init__
    super(Categorical, self).__init__(batch_shape, validate_args=validate_args)
  File "torch\distributions\distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter logits (Tensor of shape (1, 51865)) of distribution Categorical(logits: torch.Size([1, 51865])) to satisfy the constraint IndependentConstraint(Real(), 1), but found invalid values:
tensor([[nan, nan, nan,  ..., nan, nan, nan]])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 36, in main
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 52, in _freeze_support
  File "multiprocessing\spawn.py", line 116, in spawn_main
  File "multiprocessing\spawn.py", line 129, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'" like 10 times.

win11 x64 latest vision, 12650h cpu, 16G memory and I've tried tiny, small, base and medium model, but never succeeed.
Installation Path: D:\Program Files\Buzz

Did I do something wrong? Is there anyone having a same problem?

**Comment by raivisdejus** [comment]
What version are you using? Log into GitHub and download latest development build from some latest Action run. f.e. https://github.com/chidiwilliams/buzz/actions/runs/9718013525

Also you can try not setting "Word level timestamps" when you transcribe.

Another option is to try other Whisper type. On CPU Whisper.cpp will be faster and if you have GPU with at least 6GB of VRAM Faster Whisper should work the best

**Comment by nulllee** [comment]
What version are you using?：[https://github.com/chidiwilliams/buzz/releases/download/v0.9.0/Buzz-0.9.0-windows.exe](url)
"Word level timestamps". I'll try it.
As for other types, I'm using [https://github.com/Const-me/Whisper/releases/download/1.12.0/WhisperDesktop.zip](url) now. I've run it 2 times with rtx4050 for laptop today and it works properly. Thank you for your tips. Maybe I'll try [https://github.com/chidiwilliams/buzz/actions/runs/9718013525](url) and other whisper-like models.
Your avatar is fun😄.
(English is not my native language, so sorry for these possible mistakes in my words.)

**Comment by raivisdejus** [comment]
Glad you found a solution that works
