### ISSUE TITLE
failed every time when dealing with MP4

### ISSUE THREAD

**Issue by huangwei2013** [chidiwilliams/buzz#843]
version：v1.0.1 for windows

setting：
![企业微信截图_17209428263680](https://github.com/user-attachments/assets/b6b467d8-26af-4e97-9467-da1598a7025d)

error info：

```
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber\whisper_file_transcriber.py", line 99, in transcribe_whisper
  File "buzz\transcriber\whisper_file_transcriber.py", line 184, in transcribe_openai_whisper
  File "stable_whisper\whisper_word_level\original_whisper.py", line 452, in transcribe_stable
  File "stable_whisper\whisper_word_level\original_whisper.py", line 300, in detect_language
  File "tqdm\std.py", line 722, in write
AttributeError: 'NoneType' object has no attribute 'write'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 37, in main
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 122, in spawn_main
  File "multiprocessing\spawn.py", line 135, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by raivisdejus** [comment]
Indeed, there is a defect.

A workaround is to specify the language you want to transcribe and not use "Detect language". Will look to fix this

**Comment by Kevin-confessions** [comment]
I meet the [issue](https://github.com/chidiwilliams/buzz/issues/731) mentioned in that website, my suggestion is **do not close the ffmpeg prompt terminal manually when you add this task**, just wait for its disappearance, then it will proceed running automatically.
