### ISSUE TITLE
'Unhandled exception in script' error

### ISSUE THREAD

**Issue by chookster** [chidiwilliams/buzz#897]
v1.0.1
Win 11

Transcribed about 40 minutes of conversation using the Whisper Medium model OK. Then tried same recording with the Whisper Large-v3 model. It must have nearly completed the job but produced this error.

![Screenshot 2024-09-01 172241](https://github.com/user-attachments/assets/bd44f149-1ab5-4d63-8748-9b05373f1b63)

**Full text of error message.**
```
Traceback (most recent call last):
  File "whisper\transcribe.py", line 375, in transcribe
  File "tqdm\std.py", line 1242, in update
  File "tqdm\std.py", line 1347, in refresh
  File "tqdm\std.py", line 1495, in display
  File "tqdm\std.py", line 459, in print_status
  File "tqdm\std.py", line 452, in fp_write
  File "tqdm\utils.py", line 196, in inner
  File "buzz\conn.py", line 11, in write
  File "multiprocessing\connection.py", line 206, in send
  File "multiprocessing\connection.py", line 289, in _send_bytes
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber\whisper_file_transcriber.py", line 99, in transcribe_whisper
  File "buzz\transcriber\whisper_file_transcriber.py", line 202, in transcribe_openai_whisper
  File "whisper\transcribe.py", line 228, in transcribe
  File "tqdm\std.py", line 1140, in __exit__
  File "tqdm\std.py", line 1290, in close
  File "tqdm\std.py", line 1287, in fp_write
  File "tqdm\utils.py", line 196, in inner
  File "buzz\conn.py", line 11, in write
  File "multiprocessing\connection.py", line 206, in send
  File "multiprocessing\connection.py", line 289, in _send_bytes
BrokenPipeError: [WinError 232] The pipe is being closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 37, in main
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 122, in spawn_main
  File "multiprocessing\spawn.py", line 135, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

```

**Comment by chookster** [comment]
I tried the Whisper model Large-v2 and that worked OK. So re-ran the Large-v3 and that also worked OK. So the error above looks like it was generated by something I did.

**Comment by raivisdejus** [comment]
Glad it works in the end :)
