### ISSUE TITLE
RuntimeError: FFmpeg extension is not available.

### ISSUE THREAD

**Issue by mriamnobody** [chidiwilliams/buzz#923]
OS: Windows 11 (26100.1882)
Python: 3.10.7
Buzz Version: 1.1.0
CUDA Version: 12.1

Installed Buzz in venv. I used the below command:

```
pip install buzz-captions
python -m buzz
```

Also installed uninstalled torch and installed CUDA version of torch library using:

```
pip3 uninstall torch torchaudio  
pip3 install torch==2.2.1+cu121 torchaudio==2.2.1+cu121 --index-url https://download.pytorch.org/whl/cu121
```

Installed ffmpeg and ffpmeg-python using:

```
pip3 uninstall ffmpeg ffmpeg-python  
pip3 install ffmpeg
pip3 install ffmpeg-python
```
I'm getting the following error:

```
[2024-10-02 16:30:47,970] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg6
[2024-10-02 16:30:47,970] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\rosha\Downloads\buzz\buzzenv\Lib\site-packages\torio\lib\libtorio_ffmpeg6.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
[2024-10-02 16:30:47,986] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg5
[2024-10-02 16:30:47,986] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\rosha\Downloads\buzz\buzzenv\Lib\site-packages\torio\lib\libtorio_ffmpeg5.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
[2024-10-02 16:30:47,986] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg4
[2024-10-02 16:30:47,986] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 108, in _find_versionsed_ffmpeg_extension
    _load_lib(lib)
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 94, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torch\_ops.py", line 933, in load_library
    ctypes.CDLL(path)
  File "C:\Users\rosha\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'C:\Users\rosha\Downloads\buzz\buzzenv\Lib\site-packages\torio\lib\libtorio_ffmpeg4.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
[2024-10-02 16:30:47,986] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg
[2024-10-02 16:30:47,986] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
    ext = _find_versionsed_ffmpeg_extension(ffmpeg_ver)
  File "C:\Users\rosha\Downloads\buzz\buzzenv\lib\site-packages\torio\_extension\utils.py", line 106, in _find_versionsed_ffmpeg_extension
    raise RuntimeError(f"FFmpeg{version} extension is not available.")
RuntimeError: FFmpeg extension is not available.
```

Below is the list of packages installed:
```
Package            Version
------------------ -----------
annotated-types    0.7.0
anyio              4.6.0
av                 11.0.0
backports.tarfile  1.2.0
Brotli             1.1.0
buzz-captions      1.1.0
certifi            2024.8.30
cffi               1.17.1
charset-normalizer 3.3.2
colorama           0.4.6
coloredlogs        15.0.1
ctranslate2        4.4.0
dataclasses-json   0.6.7
distro             1.9.0
exceptiongroup     1.2.2
faster-whisper     1.0.1
ffmpeg             1.4
ffmpeg-python      0.2.0
filelock           3.16.1
flatbuffers        24.3.25
fsspec             2024.9.0
future             1.0.0
h11                0.14.0
httpcore           1.0.6
httpx              0.27.2
huggingface-hub    0.25.1
humanfriendly      10.0
humanize           4.10.0
idna               3.10
importlib_metadata 8.5.0
jaraco.classes     3.4.0
jaraco.context     6.0.1
jaraco.functools   4.1.0
Jinja2             3.1.4
jiter              0.5.0
keyring            25.4.1
llvmlite           0.43.0
MarkupSafe         2.1.5
marshmallow        3.22.0
more-itertools     10.5.0
mpmath             1.3.0
mutagen            1.47.0
mypy-extensions    1.0.0
networkx           3.3
numba              0.60.0
numpy              1.26.4
onnxruntime        1.19.2
openai             1.51.0
openai-whisper     20231117
packaging          24.1
pip                22.2.2
platformdirs       4.3.6
polib              1.2.0
protobuf           5.28.2
pycparser          2.22
pycryptodomex      3.20.0
pydantic           2.9.2
pydantic_core      2.23.4
PyQt6              6.6.1
PyQt6-Qt6          6.6.2
PyQt6-sip          13.6.0
pyreadline3        3.5.4
pywin32-ctypes     0.2.3
PyYAML             6.0.2
regex              2024.9.11
requests           2.32.3
safetensors        0.4.5
setuptools         63.2.0
sniffio            1.3.1
sounddevice        0.4.7
srt                3.5.3
srt_equalizer      0.1.10
stable-ts          2.15.9
sympy              1.13.3
tiktoken           0.7.0
tokenizers         0.15.2
torch              2.2.1+cu121
torchaudio         2.2.1+cu121
tqdm               4.66.5
transformers       4.39.1
typing_extensions  4.12.2
typing-inspect     0.9.0
urllib3            2.2.3
websockets         13.1
yt-dlp             2024.3.10
zipp               3.20.2
```

**EDIT 1**: Found a `ffmpeg` was installed as a `chocolatey` package. Removed the `chocolatey` package and also removed `ffmpeg` from `PATH`. But when I run `ffmpeg -version` in venv, I'm getting `'ffmpeg' is not recognized as an internal or external command, operable program or batch file.`

**EDIT 2**: The `ffmpeg` version in my PATH was `7.1` so I downloaded `ffmpeg 6.1.1` but still getting the same error.

**Comment by raivisdejus** [comment]
@mriamnobody When buzz loads a few "ffmpeg not found" errors are ok, it tries to find it by different means, but eventually it should find some and it should work. IMO best  if path to a folder with `ffmpeg` is in the Windows `Path` environment variable and  `ffmpeg -version` also works.

I tried the steps you mentioned and I also got this error, but the buzz **still worked and was transcribing** my test audio and video files.

---

Assuming it (the buzz transcription) does not work for you, see if any of the below tips help.

For `chocolatery` case try this way to install it https://docs.chocolatey.org/en-us/choco/setup/#install-with-cmdexe
It adds chocolatery installation path to the windows `PATH`. That might be the missing part, but again if `choco` is recognized so should be the `ffmpeg`

Also maybe this guide of installing https://www.geeksforgeeks.org/how-to-install-ffmpeg-on-windows/

Third option I can imagine is to check what folders are in currently defined `PATH`  environmental variable and put the `ffmpeg` of `ffmpeg.exe` in one of the existing folders in the `PATH` , say `C:\Windows\system32`

Also maybe ` pip install --force-reinstall ffmpeg ffmpeg-python` helps the situation.

**Comment by raivisdejus** [comment]
In the very latest development version I fixed an issue with regular Whisper model that was related to ffmpeg. So maybe the latest version works for you. It has GPU support already included.

To get it:
- Log into the github
- Get the installation files from the latest build https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain


Will close the issue, feel free to re-open if none of the above solved your issue.

**Comment by mriamnobody** [comment]
> In the very latest development version I fixed an issue with regular Whisper model that was related to ffmpeg. So maybe the latest version works for you. It has GPU support already included.
> 
> To get it:
> 
> * Log into the github
> * Get the installation files from the latest build https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
> 
> Will close the issue, feel free to re-open if none of the above solved your issue.

Will definitely try it. Thank you @raivisdejus for quick fix.
