### ISSUE TITLE
Unhandled Exception in Script,

### ISSUE THREAD

**Issue by vuipp** [chidiwilliams/buzz#931]
I installed buzz1.1.0 on windows 10 and got this error, can anyone help me?
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 66, in main
  File "buzz\widgets\application.py", line 37, in __init__
  File "buzz\db\db.py", line 19, in setup_app_db
  File "buzz\db\db.py", line 30, in _setup_db
  File "buzz\db\helpers.py", line 16, in copy_transcriptions_from_json_to_sqlite
sqlite3.IntegrityError: NOT NULL constraint failed: transcription.time_queued

**Comment by raivisdejus** [comment]
The error is caused by Buzz not being able to copy old tasks to the new DB. So one option is to paste this into the address bar `%USERPROFILE%\AppData\Local\Buzz` and find the `tasks.json` and delete it.

I am not fully able to replicate this error, but I added a fix that may prevent this error. So you can also test the latest development version.
1. Log into the Github
2. Download latest development version from latest development build https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

I would appreciate if you could test if the fix in latest development version works.

**Comment by vuipp** [comment]
I deleted the tasks.json file and it worked, thank you very much
