### ISSUE TITLE
Crashing when clicking record icon

### ISSUE THREAD

**Issue by morrellaberdeen** [chidiwilliams/buzz#934]
For the first time, I downloaded and installed the  .exe file (latest release) on my laptop running Windows 11.

It works well in transcribing imported files.

However, one I click the microphone icon to record, thae software crashes within 7 seconds.

**Comment by raivisdejus** [comment]
Does the bar near the record button nave some movement? 
![attels](https://github.com/user-attachments/assets/12e64c49-0f47-4c37-b4f9-c18b8c8392ac)
If not no sound is being detected on the input. 

You can check if selecting a different input device (Microphone) works.


Development note - Possibly we need to disable the "Record" button if no sound is detected on the input device selected.

**Comment by raivisdejus** [comment]
@morrellaberdeen What Whisper type and model size are you using?

Also paste `%USERPROFILE%\AppData\Local\Buzz\Buzz\Logs` into the file explorer address bar and see what information is in the `logs`  file. Check at the end of file.

**Comment by Tamosch94** [comment]
**Hello I have the same issue it says there was a connection error?** 







Traceback (most recent call last):
  File "openai\_base_client.py", line 926, in _request
  File "httpx\_client.py", line 914, in send
  File "httpx\_client.py", line 942, in _send_handling_auth
  File "httpx\_client.py", line 979, in _send_handling_redirects
  File "httpx\_client.py", line 1015, in _send_single_request
  File "httpx\_transports\default.py", line 232, in handle_request
  File "contextlib.py", line 158, in __exit__
  File "httpx\_transports\default.py", line 86, in map_httpcore_exceptions
httpx.LocalProtocolError: Illegal header value b'Bearer '
[2024-10-14 23:50:46,777] _base_client._retry_request:1012 DEBUG -> 0 retries left
[2024-10-14 23:50:46,778] _base_client._retry_request:1015 INFO -> Retrying request to /chat/completions in 1.736427 seconds
[2024-10-14 23:50:48,515] _base_client._build_request:442 DEBUG -> Request options: {'method': 'post', 'url': '/chat/completions', 'files': None, 'json_data': {'messages': [{'role': 'system', 'content': 'translate to english'}, {'role': 'user', 'content': 'So this course was designed for you to have a'}], 'model': ''}}
[2024-10-14 23:50:48,516] _trace.trace:45 DEBUG -> connect_tcp.started host='api.openai.com' port=443 local_address=None timeout=5.0 socket_options=None
[2024-10-14 23:50:48,530] _trace.trace:45 DEBUG -> connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x000001F7FF47B710>
[2024-10-14 23:50:48,530] _trace.trace:45 DEBUG -> start_tls.started ssl_context=<ssl.SSLContext object at 0x000001F7FF400320> server_hostname='api.openai.com' timeout=5.0
[2024-10-14 23:50:48,551] _trace.trace:45 DEBUG -> start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x000001F7FF47B7D0>
[2024-10-14 23:50:48,551] _trace.trace:45 DEBUG -> send_request_headers.started request=<Request [b'POST']>
[2024-10-14 23:50:48,551] _trace.trace:45 DEBUG -> send_request_headers.failed exception=LocalProtocolError(LocalProtocolError("Illegal header value b'Bearer '"))
[2024-10-14 23:50:48,552] _trace.trace:45 DEBUG -> response_closed.started
[2024-10-14 23:50:48,552] _trace.trace:45 DEBUG -> response_closed.complete
[2024-10-14 23:50:48,552] _base_client._request:947 DEBUG -> Encountered Exception
Traceback (most recent call last):
  File "httpx\_transports\default.py", line 69, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 233, in handle_request
  File "httpcore\_sync\connection_pool.py", line 216, in handle_request
  File "httpcore\_sync\connection_pool.py", line 196, in handle_request
  File "httpcore\_sync\connection.py", line 101, in handle_request
  File "httpcore\_sync\http11.py", line 143, in handle_request
  File "httpcore\_sync\http11.py", line 93, in handle_request
  File "httpcore\_sync\http11.py", line 151, in _send_request_headers
  File "contextlib.py", line 158, in __exit__
  File "httpcore\_exceptions.py", line 14, in map_exceptions
httpcore.LocalProtocolError: Illegal header value b'Bearer '

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "openai\_base_client.py", line 926, in _request
  File "httpx\_client.py", line 914, in send
  File "httpx\_client.py", line 942, in _send_handling_auth
  File "httpx\_client.py", line 979, in _send_handling_redirects
  File "httpx\_client.py", line 1015, in _send_single_request
  File "httpx\_transports\default.py", line 232, in handle_request
  File "contextlib.py", line 158, in __exit__
  File "httpx\_transports\default.py", line 86, in map_httpcore_exceptions
httpx.LocalProtocolError: Illegal header value b'Bearer '
[2024-10-14 23:50:48,556] _base_client._request:959 DEBUG -> Raising connection error

**Comment by raivisdejus** [comment]
@Tamosch94 Your error has something to do with the API token. It is invalid. Maybe not filled or filled with some non string value. 

At some later time I'll see what we can do to improve error handling for this.For now see Try to test the API token in the Preferences section.

**Comment by raivisdejus** [comment]
A check to detect unsupported characters in the API key was added to mitigate issues. 

Will close the issue, feel free to re-open if note information becomes available.
