### ISSUE TITLE
Using other than official Whisper Models

### ISSUE THREAD

**Issue by adijahangir123** [chidiwilliams/buzz#935]
Hey
I have been using buzz for sometime and it is an amazing effort. I have a question from you. If i want to use some modified or further trained whisper model, how can i use that model. As I have to use to it on system without direct internet access, how i can use a model from hugging face. Thanks in advance

**Comment by raivisdejus** [comment]
Short answer is download necessary models on some computer with internet and then copy over to the computer without the internet. 

Buzz stores models in it's cache folder. The folder is always in the same place, so you can copy it over from one computer with internet to another without the internet. To find the model folder go to Help -> Preferences -> Models. Download some models and click on the button to show model location. The folder is something like this `C:\Users\YourUserName\AppData\Local\Buzz\Buzz\Cache\models`

Also you can check this section on advanced preferences https://chidiwilliams.github.io/buzz/docs/preferences#advanced-preferences
This is a way for you to set custom model root. Might be useful.

**Comment by raivisdejus** [comment]
If you select `Huggingface` as Whisper type when you add some file to be transcribed, you will be able to enter a Huggingface model id and Buzz will download the necessary model files

**Comment by adijahangir123** [comment]
When I try to add Huggingface id to download mode, i received following error
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber\whisper_file_transcriber.py", line 97, in transcribe_whisper
  File "buzz\transcriber\whisper_file_transcriber.py", line 122, in transcribe_hugging_face
  File "buzz\transformers_whisper.py", line 170, in transcribe
  File "transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "transformers\modeling_utils.py", line 3144, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory C:\Users\hp\AppData\Local\Buzz\Buzz\Cache\models\models--lanmandragoran--urdu-whisper-large-v2\snapshots\7463b4079a018b48afc407f0e8dffe90f16368c0.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 38, in main
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 122, in spawn_main
  File "multiprocessing\spawn.py", line 135, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by adijahangir123** [comment]
M

**Comment by raivisdejus** [comment]
Buzz uses custom folders to download models, so you could move them to another system. You need to download models thru Buzz. Enter "lanman" in the search box and then select appropriate model.

Model downloading uses huggingface code to manage caches and versions so I am not sure you can download models thru browser or by other means. Best way to download models is to use Buzz to do that.  

In your case all the files you see in the huggingface repo in "Files" section
should be in `C:\Users\hp\AppData\Local\Buzz\Buzz\Cache\models\models--lanmandragoran--urdu-whisper-large-v2\snapshots\7463b4079a018b48afc407f0e8dffe90f16368c0`

Error you get is saying that it can't find the model files.

**Comment by dra6on1** [comment]
I tried downloading through Buzz the large-v3-turbo model using huggingface and hit the same type of errors.

after attempting to download for about 5-10 seconds and sitting at 1% it throws shows a window with the title of "Unhandled exception in script"
just below that it says "Failed to execute script 'main' due to unhandled exception: 'NoneType' object has no attribute 'write'

then in its main display it says the following lines -
Traceback (most recent call last):
  File "multiprocessing\process.py", line 314, in _bootstrap
  File "multiprocessing\process.py", line 108, in run
  File "buzz\transcriber\whisper_file_transcriber.py", line 97, in transcribe_whisper
  File "buzz\transcriber\whisper_file_transcriber.py", line 122, in transcribe_hugging_face
  File "buzz\transformers_whisper.py", line 170, in transcribe
  File "transformers\models\auto\auto_factory.py", line 563, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "transformers\modeling_utils.py", line 3144, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory C:\Users\sssss\AppData\Local\Buzz\Buzz\Cache\models\models--openai--whisper-large-v3-turbo\snapshots\41f01f3fe87f28c78e2fbf8b568835947dd65ed9.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "buzz\buzz.py", line 38, in main
  File "PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 50, in _freeze_support
  File "multiprocessing\spawn.py", line 122, in spawn_main
  File "multiprocessing\spawn.py", line 135, in _main
  File "multiprocessing\process.py", line 329, in _bootstrap
AttributeError: 'NoneType' object has no attribute 'write'

**Comment by raivisdejus** [comment]
@dra6on1 @adijahangir123 

Open the models folder you see in the error, f.e. `C:\Users\sssss\AppData\Local\Buzz\Buzz\Cache\models` 
Delete the turbo model folder
Try to download again

I have seen random network errors from time to time, but usually retrying the download it eventually succeeds.

**Comment by dra6on1** [comment]
That  worked. It may be worth adding that as a note to the bottom  of the error output so people know to try it.

**Comment by raivisdejus** [comment]
A mitigation to possible model download issues was added. If download fails the incomplete model download will be deleted so Buzz will automatically try to re-download it. 

Also there is a note in the FAQ section on this.
