### ISSUE TITLE
[Question]Transcibe youtube video using URL

### ISSUE THREAD

**Issue by mriamnobody** [chidiwilliams/buzz#936]
Is there any way to directly transcribe a youtube video via the URL instead of downloading it and feeding to Buzz?

**Comment by raivisdejus** [comment]
File -> Import url should to this, but I see that there is some bug right now.

**Comment by raivisdejus** [comment]
@mriamnobody Url import has now been fixed. You can test it from the latest development build.

1. Log into the Github
2. Get the installation files from latest development build https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain

**Comment by mriamnobody** [comment]
Thanks for quick update @raivisdejus. I have downloaded and installed the build from the above mentioned link. I can now add a url for transcription or translation from Youtube but the issue now is that the Buzz terminates abruptly without an alert or error. I have attached log file content.

```

[2024-10-08 12:13:17,994] locale.<module>:12 DEBUG -> UI locales ['en-IN', 'en-Latn-IN', 'en-US', 'en-Latn-US', 'en', 'hi', 'hi-Deva-IN', 'hi-IN']
[2024-10-08 12:13:18,000] model_loader.<module>:42 DEBUG -> Model root directory: C:\Users\rosha\AppData\Local\Buzz\Buzz\Cache\models
[2024-10-08 12:13:19,042] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg6
[2024-10-08 12:13:19,042] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg6 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-10-08 12:13:19,043] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg5
[2024-10-08 12:13:19,043] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg5 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-10-08 12:13:19,043] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg4
[2024-10-08 12:13:19,043] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg4 extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-10-08 12:13:19,044] utils._find_ffmpeg_extension:114 DEBUG -> Loading FFmpeg
[2024-10-08 12:13:19,044] utils._find_ffmpeg_extension:120 DEBUG -> Failed to load FFmpeg extension.
Traceback (most recent call last):
  File "torio\_extension\utils.py", line 116, in _find_ffmpeg_extension
  File "torio\_extension\utils.py", line 105, in _find_versionsed_ffmpeg_extension
  File "<frozen importlib.util>", line 95, in find_spec
ModuleNotFoundError: No module named 'torio.lib'
[2024-10-08 12:13:19,125] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-08 12:13:19,136] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-08 12:13:19,137] buzz.main:61 DEBUG -> app_dir: C:\Program Files (x86)\Buzz\_internal
[2024-10-08 12:13:19,137] buzz.main:62 DEBUG -> log_dir: C:\Users\rosha\AppData\Local\Buzz\Buzz\Logs
[2024-10-08 12:13:19,137] buzz.main:63 DEBUG -> cache_dir: C:\Users\rosha\AppData\Local\Buzz\Buzz\Cache
[2024-10-08 12:13:19,137] buzz.main:64 DEBUG -> data_dir: C:\Users\rosha\AppData\Local\Buzz\Buzz
[2024-10-08 12:13:19,159] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-08 12:13:19,169] db._setup_db:39 DEBUG -> Database connection opened: C:\Users\rosha\AppData\Local\Buzz\Buzz\Buzz.sqlite
[2024-10-08 12:13:19,179] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-08 12:13:19,207] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-08 12:13:19,288] file_transcriber_queue_worker.run:40 DEBUG -> Waiting for next transcription task
[2024-10-08 12:13:28,634] backend._load_plugins:205 DEBUG -> Loading KWallet
[2024-10-08 12:13:28,634] backend._load_plugins:205 DEBUG -> Loading SecretService
[2024-10-08 12:13:28,635] backend._load_plugins:205 DEBUG -> Loading Windows
[2024-10-08 12:13:28,637] __init__.<module>:11 DEBUG -> Loaded cffi backend
[2024-10-08 12:13:28,657] backend._load_plugins:205 DEBUG -> Loading chainer
[2024-10-08 12:13:28,657] backend._load_plugins:205 DEBUG -> Loading libsecret
[2024-10-08 12:13:28,658] backend._load_plugins:205 DEBUG -> Loading macOS
[2024-10-08 12:13:28,672] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-08 12:13:28,676] settings.__init__:14 DEBUG -> Settings filename: \HKEY_CURRENT_USER\Software\Buzz\OrganizationDefaults
[2024-10-08 12:13:34,888] file_transcriber_queue_worker.run:56 DEBUG -> Starting next transcription task
```

One more query, Is the Buzz installed in venv?

**Comment by raivisdejus** [comment]
@mriamnobody If you install Buzz with the installation `*.exe` it will be in sort of venv. It will come with all packages packaged separately and also it's own python, so packages Buzz needs will not be added to system python env.

If you install it via PIP, it is up to you to add it to a venv.

 The above errors seem fine. Buss will try to load `ffmpeg` by different means, while trying to do os there are errors, but usually it finds it eventually. So these errors are fine, there may be other errors later in the logs. 

Does the Buzz work for downloaded audio or video files? You could try to install `ffmpeg` in your system, but this is sort of a guess, should not be an issue in normal cases.

**Comment by mriamnobody** [comment]
OS: Windows 11 (26100.1882)
Python: 3.10.7
Buzz Version: 1.1.0
CUDA Version: 12.1
ffmpeg version on path:  6.1.1

PIP list:

```
Package                   Version
------------------------- ------------
aiohappyeyeballs          2.4.0
aiohttp                   3.10.6
aiosignal                 1.3.1
alembic                   1.13.1
androguard                4.0.2
anyio                     4.0.0
apkInspector              1.2.1
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.2.3
asn1crypto                1.5.1
asttokens                 2.4.0
async-lru                 2.0.4
async-timeout             4.0.3
asyncqt                   0.8.0
attrs                     23.1.0
Babel                     2.12.1
backcall                  0.2.0
banal                     1.0.6
beautifulsoup4            4.12.2
bleach                    6.0.0
blinker                   1.7.0
bs4                       0.0.2
certifi                   2023.7.22
cffi                      1.15.1
charset-normalizer        3.2.0
clean-fid                 0.1.35
cli-helpers               2.3.0
click                     8.1.7
cloudpickle               3.0.0
colorama                  0.4.6
comm                      0.1.4
configobj                 5.0.8
contourpy                 1.2.0
cryptg                    0.4.0
cycler                    0.12.1
dataset                   1.6.2
debugpy                   1.8.0
decorator                 5.1.1
defusedxml                0.7.1
delegator.py              0.1.1
distlib                   0.3.7
et-xmlfile                1.1.0
exceptiongroup            1.1.3
executing                 1.2.0
fastjsonschema            2.18.0
ffmpeg                    1.4
ffmpeg-python             0.2.0
filelock                  3.12.4
Flask                     3.0.0
Flask-SQLAlchemy          3.1.1
fonttools                 4.47.0
fqdn                      1.5.1
frida                     16.0.3
frida-tools               12.0.3
frozenlist                1.4.1
future                    1.0.0
greenlet                  3.0.3
h11                       0.14.0
httpcore                  1.0.4
httpx                     0.27.0
idna                      3.4
ipykernel                 6.25.2
ipython                   8.15.0
isoduration               20.11.0
itsdangerous              2.1.2
jedi                      0.19.0
Jinja2                    3.1.2
json5                     0.9.14
jsonpointer               2.4
jsonschema                4.19.1
jsonschema-specifications 2023.7.1
jupyter_client            8.3.1
jupyter_core              5.3.1
jupyter-events            0.7.0
jupyter-lsp               2.2.0
jupyter_server            2.7.3
jupyter_server_terminals  0.4.4
jupyterlab                4.0.6
jupyterlab-pygments       0.2.2
jupyterlab_server         2.25.0
kiwisolver                1.4.5
litecli                   1.10.0
loguru                    0.7.2
lxml                      5.1.0
Mako                      1.3.0
MarkupSafe                2.1.3
matplotlib                3.8.2
matplotlib-inline         0.1.6
meson                     1.3.1
mistune                   3.0.1
MouseInfo                 0.1.3
mpmath                    1.3.0
multidict                 6.1.0
mutf8                     1.0.6
nbclient                  0.8.0
nbconvert                 7.8.0
nbformat                  5.9.2
nest-asyncio              1.5.8
networkx                  3.1
notebook_shim             0.2.3
numpy                     1.26.0
objection                 1.11.0
opencv-python             4.8.1.78
openpyxl                  3.1.5
outcome                   1.3.0.post0
overrides                 7.4.0
packaging                 23.1
pandas                    2.1.4
pandocfilters             1.5.0
parso                     0.8.3
pexpect                   4.9.0
pickleshare               0.7.5
Pillow                    10.0.1
pip                       24.0
pipdeptree                2.13.0
platformdirs              3.10.0
prometheus-client         0.17.1
prompt-toolkit            3.0.39
psutil                    5.9.5
ptyprocess                0.7.0
pure-eval                 0.2.2
pyaes                     1.6.1
pyasn1                    0.5.1
PyAutoGUI                 0.9.54
pycparser                 2.21
pydot                     2.0.0
PyGetWindow               0.0.9
Pygments                  2.16.1
PyMsgBox                  1.0.9
PyMuPDF                   1.24.7
PyMuPDFb                  1.24.6
pyparsing                 3.1.1
PyPDF2                    3.0.1
pyperclip                 1.8.2
PyQt6                     6.7.0
PyQt6-Qt6                 6.7.0
PyQt6-sip                 13.6.0
PyRect                    0.2.0
PyScreeze                 0.1.30
PySide6                   6.7.1
PySide6_Addons            6.7.1
PySide6_Essentials        6.7.1
PySocks                   1.7.1
python-dateutil           2.8.2
python-docx               1.1.0
python-json-logger        2.0.7
python-telegram-bot       21.0.1
pytweening                1.0.7
pytz                      2023.3.post1
pywin32                   306
pywinpty                  2.0.11
PyYAML                    6.0.1
pyzmq                     25.1.1
qasync                    0.27.1
redis                     5.0.1
referencing               0.30.2
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.10.3
rsa                       4.9
scipy                     1.11.2
seaborn                   0.13.1
selenium                  4.16.0
semver                    2.13.0
Send2Trash                1.8.2
setuptools                69.0.3
shiboken6                 6.7.1
six                       1.16.0
sniffio                   1.3.0
sortedcontainers          2.4.0
soupsieve                 2.5
spyder-kernels            2.5.0
SQLAlchemy                2.0.29
sqlparse                  0.4.4
stack-data                0.6.2
sympy                     1.12
tabulate                  0.9.0
Telethon                  1.35.0
terminado                 0.17.1
tinycss2                  1.2.1
tomli                     2.0.1
tornado                   6.3.3
tqdm                      4.66.1
traitlets                 5.10.0
trio                      0.23.2
trio-websocket            0.11.1
typing_extensions         4.8.0
tzdata                    2023.3
uri-template              1.3.0
urllib3                   2.0.5
virtualenv                20.24.5
wcwidth                   0.2.6
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.3
Werkzeug                  3.0.1
wheel                     0.42.0
win32-setctime            1.1.0
wordcloud                 1.9.3
wsproto                   1.2.0
yarl                      1.12.1
```

> Does the Buzz work for downloaded audio or video files?

Yes it is working as expected for audio and video files.

> You could try to install `ffmpeg` in your system, but this is sort of a guess, should not be an issue in normal cases.

I have both `ffmpeg` in path as well as installed via pip as you mention [here](https://github.com/chidiwilliams/buzz/issues/923#issuecomment-2389308526) using command `pip install --force-reinstall ffmpeg ffmpeg-python`

**Comment by raivisdejus** [comment]
@mriamnobody Utility that downloads form Youtube crashes in the app when it is installed with the installation `.exe`. It works when I run the Buzz crom the command line as described here https://github.com/chidiwilliams/buzz/blob/main/CONTRIBUTING.md#windows

Pip packages from the latest build may also work, did not test them.

Please use some workaround wile we figure out what is broken in the download utitily. e.g. download audio manually with https://github.com/yt-dlp/yt-dlp or run Buzz from command line

**Comment by mriamnobody** [comment]
@raivisdejus 

I just wanted to take a moment to thank you for not only implementing the requested features like dark mode and GPU support so quickly, but also for being so prompt in fixing any bugs that pop up with those new additions.

The main reason I initially went with the PIP installation was because of the GPU support. But since you’ve added both dark mode and GPU support to the .exe, I switched to it and it's been great to use.

Just curious—have the PIP packages been updated to include dark mode as well?

For now, the URL feature isn’t a deal-breaker for me, but I’ll definitely be using it frequently in coming time. Thanks again for all your hard work on this!

**Comment by raivisdejus** [comment]
Every development build adds all the installation files to it's artifacts section. When we have a release all the artifact files are added to release section and uploaded to all the systems that are used to distribute installation files.

So latest PIP wheel files are available in latest development builds, but to the main PIP repository they will be deployed when the next release happens. It should come some time soon.

**Comment by raivisdejus** [comment]
@mriamnobody Fix for transcribing directly from Youtube url (or urls form many other sites) is now available in the latest development version https://github.com/chidiwilliams/buzz/actions/workflows/ci.yml?query=branch%3Amain
